import type { Metadata } from "next";
import { buildMetadata } from "@/lib/seo/metadata";
import { Container } from "@/components/layout/Container";
import { Section } from "@/components/layout/Section";
import { siteConfig } from "@/config/site/site";

export const metadata: Metadata = buildMetadata({
  title: "Disclaimer",
  description: `Important information about the content and tools on ${siteConfig.url}.`,
  path: "/disclaimer",
});

export default function DisclaimerPage() {
  return (
    <>
      <Section tone="ink">
        <Container>
          <div className="flex items-center gap-3 text-xs font-medium uppercase tracking-[0.28em] text-body-dark">
            <span className="inline-block h-2 w-2 rounded-full bg-accent" />
            Legal
          </div>
          <h1 className="mt-6 text-4xl font-semibold tracking-tight text-white sm:text-5xl">
            Disclaimer
          </h1>
          <p className="mt-4 text-sm text-body-dark">Last updated: 20 July 2026</p>
        </Container>
      </Section>

      <Section tone="paper">
        <Container>
          <div className="max-w-3xl space-y-10 text-sm leading-relaxed text-body">
            <section>
              <h2 className="text-lg font-semibold tracking-tight text-heading">
                1. General information only
              </h2>
              <p className="mt-3">
                The content on {siteConfig.url}, including articles, case
                studies, guides, and downloadable resources, is provided for
                general informational purposes only. It does not constitute
                professional engineering, financial, legal, or regulatory
                advice.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold tracking-tight text-heading">
                2. No professional advice
              </h2>
              <p className="mt-3">
                Results generated by the Readiness Assessment, Fuel Selection
                Calculator, or any other interactive tool on this site are
                directional and illustrative, based solely on the answers you
                provide. They are not a substitute for a formal engineering
                evaluation carried out by a qualified engineer, and should
                not be used as the sole basis for any investment,
                procurement, or operational decision.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold tracking-tight text-heading">
                3. No guarantee of results
              </h2>
              <p className="mt-3">
                Case studies, metrics, and figures referenced on this site
                describe outcomes from specific engagements and are not a
                guarantee of similar results for any other project. Actual
                outcomes depend on factors specific to each engagement.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold tracking-tight text-heading">
                4. External links
              </h2>
              <p className="mt-3">
                This site may reference or link to third-party standards,
                regulations, or organizations (including the IMO). We are not
                affiliated with these organizations unless explicitly stated,
                and we are not responsible for the accuracy of external
                content.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold tracking-tight text-heading">
                5. Limitation of liability
              </h2>
              <p className="mt-3">
                To the fullest extent permitted by law, {siteConfig.name}{" "}
                disclaims all liability for any loss or damage arising from
                reliance on information or tool output provided on this site.
                For a project-specific evaluation, please{" "}
                <a href="/contact" className="text-heading underline underline-offset-2">
                  contact our engineering team
                </a>
                .
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold tracking-tight text-heading">
                6. Contact us
              </h2>
              <p className="mt-3">
                Questions about this disclaimer can be sent to{" "}
                <a href={`mailto:${siteConfig.email}`} className="text-heading underline underline-offset-2">
                  {siteConfig.email}
                </a>
                .
              </p>
            </section>
          </div>
        </Container>
      </Section>
    </>
  );
}
